Repository openshift-knative/operator, pull requests merged in 2020-06, with the labels that each got.

#5 Adjust 0.14 serving manifest with Openshift specifica.
  cmd/serving-operator/kodata/knative-serving/2-serving-core.yaml
  cmd/serving-operator/kodata/knative-serving/3-serving-hpa.yaml
  cmd/serving-operator/kodata/knative-serving/4-net-istio.yaml
Labels: approved, lgtm

#6 CI was here...:fire:
  ci
Labels: approved, lgtm

#7 Tmp fixing the value of the webhook to avoid OOM
  cmd/eventing-operator/kodata/knative-eventing/1-eventing.yaml
Labels: approved, lgtm

#10 Don't delete deployments first explicitly.
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved

#11 [SRVKS-575] Abort reconcilation on finalizer patch errors.
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, do-not-merge/hold, lgtm

#12 [SRVKS-452] Bump webhook memory limit to 1G.
  cmd/serving-operator/kodata/knative-serving/2-serving-core.yaml
Labels: approved, do-not-merge/hold

#13 [SRVKS-576] Don't ship gcr.io references at all.
  cmd/eventing-operator/kodata/knative-eventing/1-eventing.yaml
  cmd/eventing-operator/kodata/knative-eventing/2-upgrade-to-v0.14.2.yaml
  cmd/serving-operator/kodata/knative-serving/2-serving-core.yaml
  cmd/serving-operator/kodata/knative-serving/3-serving-hpa.yaml
Labels: approved, lgtm

#9 Updating the operator defaults for our offering
  pkg/reconciler/knativeeventing/common/defaultbroker.go
  pkg/reconciler/knativeeventing/common/defaultbroker_test.go
Labels: approved, lgtm

#14 Setting here default too
  cmd/eventing-operator/kodata/knative-eventing/1-eventing.yaml
Labels: approved, lgtm

#15 Add openshift hacks
  Dockerfile
  OWNERS
Labels: approved
