Repository openshift-knative/operator, pull requests merged in 2020-09, with the labels that each got.

#39 Changing SINK_BINDING_SELECTION_MODE default to inclusion
  cmd/operator/kodata/knative-eventing/0.17.0/3-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.2/2-eventing-core.yaml
Labels: approved, lgtm

#40 SRVKE-470 moving forward to 0.15.x
  cmd/operator/kodata/knative-eventing/0.15.2/2-upgrade-to-v0.15.2.yaml
Labels: approved, lgtm

#44 fix default metrics port
  cmd/operator/kodata/knative-eventing/0.15.2/1-eventing.yaml
Labels: approved, lgtm, ok-to-test

#45 Remove net-istio from our fork for v0.16
  cmd/operator/kodata/knative-serving/0.16.0/4-net-istio.yaml
Labels: approved, lgtm

#46 Hardcode job name in the post install job to be overridable.
  cmd/operator/kodata/knative-serving/0.16.0/5-serving-post-install-jobs.yaml
Labels: approved, lgtm

#47 Move the missing roles to the 0.15 - this now matches upstream 0.17+
  cmd/operator/kodata/knative-eventing/0.15.2/1-eventing.yaml
Labels: approved

#48 Move the missing parts for the 'edit' role to the 0.16 - this now matches upstream 0.17+
  cmd/operator/kodata/knative-eventing/0.16.1/2-eventing.yaml
Labels: approved

#49 Add sugar controller ocp 016
  cmd/operator/kodata/knative-eventing/0.16.0/3-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.16.0/4-eventing-post-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.16.1/3-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.16.1/4-eventing-post-install-jobs.yaml
Labels: approved, lgtm

#50 [RELEASE-0.17] Updates to make Serving 0.17.3 happen
  cmd/operator/kodata/knative-serving/0.17.1/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.17.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.17.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.17.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.17.3/5-serving-post-install-jobs.yaml
Labels: approved, lgtm

#51 [RELEASE-0.16] Read images from environment in the upstream operator
  pkg/reconciler/common/image_override.go
  pkg/reconciler/common/image_override_test.go
  pkg/reconciler/common/transformers.go
Labels: approved, lgtm

#52 [RELEASE-0.17] Read images from environment in the upstream operator (#51)
  pkg/reconciler/common/image_override.go
  pkg/reconciler/common/image_override_test.go
  pkg/reconciler/common/transformers.go
Labels: approved, lgtm
